#!/usr/bin/env python
# -*- coding: utf8 -*-
"""
Copyright (C) 2011 Tyler Kennedy <tk@tkte.ch>

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""
import sys
import getopt

from opennbt import NBTFile


def usage(path):
    print('Dumps a NBT structure in a human-readable format.')
    print('Usage: %s [options] file1 file2 ...' % path)
    print('-h/--help')
    print('\tPrints this message and quits.')
    print('-o/--output [file]')
    print('\tWrite output to a file.')
    print('-u/--uncompressed')
    print('\tDo not assume the input is compressed.')

if __name__ == '__main__':
    try:
        opts, args = getopt.gnu_getopt(
            sys.argv[1:],
            'ho:u',
            [
                'help',
                'output=',
                'uncompressed'
            ]
        )
    except getopt.GetoptError, e:
        print(str(e))
        sys.exit(2)

    output = sys.stdout
    compressed = True

    for o, a in opts:
        if o in ('-h', '--help'):
            usage(sys.argv[0])
            sys.exit(0)
        elif o in ('-o', '--output'):
            output = a
        elif o in ('-u', '--uncompressed'):
            compressed = False
        else:
            print('Unknown option %r!' % o)
            usage(sys.argv[0])
            sys.exit(2)

    if not args:
        usage(sys.argv[0])
        sys.exit(0)

    out = open(output, 'wb') if isinstance(output, basestring) else output

    for arg in args:
        n = NBTFile(arg, compressed=compressed)
        out.write(n.pretty())

    if isinstance(output, basestring):
        out.close()
