#!/usr/bin/env python
# -*- coding: utf8 -*-
import sys
import getopt

from pynbt import RegionFile


def usage(path):
    pass


if __name__ == '__main__':
    try:
        opts, args = getopt.gnu_getopt(
            sys.argv[1:],
            'ho:',
            [
                'help',
                'output='
            ]
        )
    except getopt.GetoptError, e:
        print(str(e))
        sys.exit(2)

    output = sys.stdout

    for o, a in opts:
        if o in ('-h', '--help'):
            usage(sys.argv[0])
            sys.exit(0)
        elif o in ('-o', '--output'):
            output = a
        else:
            print('Unknown option %r!' % o)
            usage(sys.argv[0])
            sys.exit(2)

    if not args:
        usage(sys.argv[0])
        sys.exit(0)

    out = open(output, 'wb') if isinstance(output, basestring) else output

    for arg in args:
        n = RegionFile(arg)
        out.write(n.pretty())
        out.write('\n')

    if isinstance(output, basestring):
        out.close()

