#!/usr/bin/env python
# -*- coding: utf8 -*-
import sys
import getopt

from pynbt import NBTFile


def usage(path):
    print('Dumps a NBT structure in a human-readable format.')
    print('Usage: %s [options] file1 file2 ...' % path)
    print('-h/--help')
    print('\tPrints this message and quits.')
    print('-o/--output [file]')
    print('\tWrite output to a file.')
    print('-u/--uncompressed')
    print('\tDo not assume the input is compressed.')

if __name__ == '__main__':
    try:
        opts, args = getopt.gnu_getopt(
            sys.argv[1:],
            'ho:u',
            [
                'help',
                'output=',
                'uncompressed'
            ]
        )
    except getopt.GetoptError, e:
        print(str(e))
        sys.exit(2)

    output = sys.stdout
    compressed = True

    for o, a in opts:
        if o in ('-h', '--help'):
            usage(sys.argv[0])
            sys.exit(0)
        elif o in ('-o', '--output'):
            output = a
        elif o in ('-u', '--uncompressed'):
            compressed = False
        else:
            print('Unknown option %r!' % o)
            usage(sys.argv[0])
            sys.exit(2)

    if not args:
        usage(sys.argv[0])
        sys.exit(0)

    out = open(output, 'wb') if isinstance(output, basestring) else output

    for arg in args:
        n = NBTFile(arg, compressed=compressed)
        out.write(n.pretty())
        out.write('\n')

    if isinstance(output, basestring):
        out.close()
